SDL2:
  name: "SDL2"
  url: "https://www.libsdl.org/release/SDL2-2.0.4.zip"
  filename: "SDL2-2.0.4.zip"
  folder: "SDL2-2.0.4"
  extension: "zip"
  patches:
    -
      name: "fPIC"
      filename: "CMakeLists.txt.patch"
      src: "."
      dst: "."

SDL2_mixer:
  name: "SDL2_mixer"
  url: "https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.zip"
  filename: "SDL2_mixer-2.0.1.zip"
  folder: "SDL2_mixer-2.0.1"
  extension: "zip"
  patches:
    -
      name: "SDL location"
      filename: "project.pbxproj.patch"
      src: "."
      dst: "Xcode-iOS/SDL_mixer.xcodeproj"
    -
      name: "Android Build"
      filename: "Android.mk.patch"
      src: "."
      dst: "."
    -
      name: "fPIC"
      filename: "Makefile.in.patch"
      src: "."
      dst: "."
  injections:
    -
      name: "Android Application Def"
      filename: "Application.mk"
      src: "."
      dst: "."

freetype:
  name: "freetype"
  url: "http://ftp.igh.cnrs.fr/pub/nongnu/freetype/freetype-2.6.2.tar.gz"
  filename: "freetype-2.6.2.tar.gz"
  folder: "freetype-2.6.2"
  extension: "tar.gz"
  patches:
    -
      name: "CMake Lists"
      filename: "CMakeLists.txt.patch"
      src: "."
      dst: "."
    -
      name: "iOS CMake"
      filename: "iOS.cmake.patch"
      src: "."
      dst: "builds/cmake"
  injections:
    -
      name: "Android Toolchain"
      filename: "android.toolchain.cmake"
      src: "."
      dst: "builds/cmake"

freetype-gl:
  name: "freetype-gl"
  url: "https://codeload.github.com/rougier/freetype-gl/zip/master"
  filename: "freetype-gl.zip"
  folder: "freetype-gl-master"
  extension: "zip"
  patches:
    -
      name: "CMake Lists"
      filename: "CMakeLists.txt.patch"
      src: "."
      dst: "."
    -
      name: "OpenGL"
      filename: "opengl.h.patch"
      src: "."
      dst: "."
  injections:
    -
      name: "iOS CMake"
      filename: "iOS.cmake"
      src: "."
      dst: "CMakeModules"
    -
      name: "Android Toolchain"
      filename: "android.toolchain.cmake"
      src: "."
      dst: "CMakeModules"

gtest:
  name: "gtest"
  url: "https://codeload.github.com/google/googletest/zip/release-1.7.0"
  filename: "gtest.zip"
  folder: "googletest-release-1.7.0"
  extension: "zip"
